version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/matebot

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - matebot-{{ checksum "pom.xml" }}

      - run: mvn package -DskipTests

      - save_cache:
          paths:
            - ~/.m2
          key: matebot-{{ checksum "pom.xml" }}

      - run: ssh-keyscan $MATEBOT_HOST >> ~/.ssh/known_hosts

      - add_ssh_keys:
          fingerprints:
            - "56:7e:3e:59:6a:f3:ba:cf:8d:1d:08:f6:37:22:5a:35"
            
      # Deploy    
      - run: |
          cd deploy
          sh publish.sh      
